development:
  adapter: postgresql
  encoding: unicode
  database: artists_development
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: artists_test
  pool: 5
  username:
  password:
